name: Build site assets (Tailwind + routes)

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.html"
      - "**/*.js"
      - "src/**"
      - "assets/**"
      - "tailwind.config.js"
      - "postcss.config.js"
      - "package.json"
      - "package-lock.json"
      - "routes.json"
      - "build_routes.ps1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          version: '7.4.x'

      - name: Generate extensionless routes (optional)
        run: npm run build:routes

      - name: Commit built files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "build: assets and routes"
            git push
          fi
