name: Build Tailwind

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.html"
      - "**/*.js"
      - "src/**"
      - "tailwind.config.js"
      - "postcss.config.js"
      - ".github/workflows/build.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Tailwind CSS
        run: |
          mkdir -p assets
          npx --yes tailwindcss@3.4.10 -i src/input.css -o assets/tailwind.css -m

      - name: List assets (debug)
        run: ls -la assets || true

      - name: Commit built CSS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "build: tailwind.css"
            git push
          fi
