name: Build Tailwind

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.html"
      - "**/*.js"
      - "src/**"
      - "tailwind.config.js"
      - "postcss.config.js"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # DO NOT disable credentials; we need them to push

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # If you do not have package-lock.json yet, npm ci will fail.
      # This conditional installs properly either way.
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build Tailwind CSS
        run: |
          mkdir -p assets
          npx tailwindcss -i src/input.css -o assets/tailwind.css -m

      # Debug: show files so we know the CSS was created
      - name: List repo root
        run: ls -la

      - name: List assets
        run: ls -la assets || true

      # Commit built CSS
      - name: Commit built CSS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "build: tailwind.css"
            git push
          fi
